services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes: ["pgdata:/var/lib/postgresql/data"]
    ports: ["5432:5432"]
  api:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --reload
    ports: ["8000:8000"]
    env_file: .env
    depends_on: [db]
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # Using Vite dev server for development
    command: yarn dev --host 0.0.0.0
    ports: ["80:5173"]
    depends_on: [api]
    volumes:
      - ./frontend:/app
      - /app/node_modules
volumes: { pgdata: {} }
