import { Lead } from "../types/lead";

// Mock data based on the CSV file
export const mockLeads: Lead[] = [
  {
    id: "1001",
    name: "Chris Underwood",
    contactInfo: "chris.underwood@example.com",
    source: "Referral",
    interestLevel: "Medium",
    status: "New",
    assignedSalesperson: "Alice",
  },
  {
    id: "1002",
    name: "Amy Davidson",
    contactInfo: "amy.davidson@example.com",
    source: "Referral",
    interestLevel: "High",
    status: "New",
    assignedSalesperson: "Alice",
  },
  {
    id: "1003",
    name: "Nicholas Campbell",
    contactInfo: "nicholas.campbell@example.com",
    source: "Website",
    interestLevel: "Low",
    status: "New",
    assignedSalesperson: "Alice",
  },
  {
    id: "1004",
    name: "Debbie Harper",
    contactInfo: "debbie.harper@example.com",
    source: "Cold Call",
    interestLevel: "Medium",
    status: "Closed",
    assignedSalesperson: "Alice",
  },
  {
    id: "1005",
    name: "Carl Caldwell",
    contactInfo: "carl.caldwell@example.com",
    source: "Referral",
    interestLevel: "High",
    status: "Qualified",
    assignedSalesperson: "Diane",
  },
  {
    id: "1006",
    name: "Drew Bird",
    contactInfo: "drew.bird@example.com",
    source: "Website",
    interestLevel: "Low",
    status: "Closed",
    assignedSalesperson: "Diane",
  },
  {
    id: "1007",
    name: "Patrick Cross",
    contactInfo: "patrick.cross@example.com",
    source: "Cold Call",
    interestLevel: "Medium",
    status: "Closed",
    assignedSalesperson: "Charlie",
  },
  {
    id: "1008",
    name: "Melissa Garcia",
    contactInfo: "melissa.garcia@example.com",
    source: "Website",
    interestLevel: "High",
    status: "New",
    assignedSalesperson: "Diane",
  },
  {
    id: "1009",
    name: "Jacqueline Simmons",
    contactInfo: "jacqueline.simmons@example.com",
    source: "Cold Call",
    interestLevel: "Medium",
    status: "Qualified",
    assignedSalesperson: "Diane",
  },
  {
    id: "1010",
    name: "Renee Garcia",
    contactInfo: "renee.garcia@example.com",
    source: "Referral",
    interestLevel: "High",
    status: "New",
    assignedSalesperson: "Charlie",
  },
  {
    id: "1011",
    name: "Stacey Campbell",
    contactInfo: "stacey.campbell@example.com",
    source: "Event",
    interestLevel: "Medium",
    status: "New",
    assignedSalesperson: "Diane",
  },
  {
    id: "1012",
    name: "Robin Henderson",
    contactInfo: "robin.henderson@example.com",
    source: "Website",
    interestLevel: "Low",
    status: "Contacted",
    assignedSalesperson: "Charlie",
  },
  {
    id: "1013",
    name: "Donna Boyd",
    contactInfo: "donna.boyd@example.com",
    source: "Cold Call",
    interestLevel: "Medium",
    status: "New",
    assignedSalesperson: "Diane",
  },
  {
    id: "1014",
    name: "Timothy Rios",
    contactInfo: "timothy.rios@example.com",
    source: "Event",
    interestLevel: "High",
    status: "Closed",
    assignedSalesperson: "Charlie",
  },
  {
    id: "1015",
    name: "Brandon Morgan",
    contactInfo: "brandon.morgan@example.com",
    source: "Referral",
    interestLevel: "Low",
    status: "New",
    assignedSalesperson: "Bob",
  },
  {
    id: "1016",
    name: "Tracy Clark",
    contactInfo: "tracy.clark@example.com",
    source: "Cold Call",
    interestLevel: "Low",
    status: "Contacted",
    assignedSalesperson: "Diane",
  },
  {
    id: "1017",
    name: "Mary Mason",
    contactInfo: "mary.mason@example.com",
    source: "Website",
    interestLevel: "Low",
    status: "Contacted",
    assignedSalesperson: "Alice",
  },
  {
    id: "1018",
    name: "Nancy Rivera",
    contactInfo: "nancy.rivera@example.com",
    source: "Website",
    interestLevel: "Medium",
    status: "New",
    assignedSalesperson: "Bob",
  },
  {
    id: "1019",
    name: "Julie Norris",
    contactInfo: "julie.norris@example.com",
    source: "Referral",
    interestLevel: "High",
    status: "Qualified",
    assignedSalesperson: "Bob",
  },
  {
    id: "1020",
    name: "Laura Silva",
    contactInfo: "laura.silva@example.com",
    source: "Event",
    interestLevel: "Medium",
    status: "Closed",
    assignedSalesperson: "Diane",
  },
];
